python/2.7.14-foss-2018a(32):ERROR:150: Module 'python/2.7.14-foss-2018a' conflicts with the currently loaded module(s) 'python/3.7.2-foss-2018a'
python/2.7.14-foss-2018a(32):ERROR:102: Tcl command execution failed: conflict python

foss/2019a(23):ERROR:150: Module 'foss/2019a' conflicts with the currently loaded module(s) 'foss/2018a'
foss/2019a(23):ERROR:102: Tcl command execution failed: conflict foss

python/2.7.15-foss-2019a(38):ERROR:150: Module 'python/2.7.15-foss-2019a' conflicts with the currently loaded module(s) 'python/3.7.2-foss-2018a'
python/2.7.15-foss-2019a(38):ERROR:102: Tcl command execution failed: conflict python

foss/2019a(23):ERROR:150: Module 'foss/2019a' conflicts with the currently loaded module(s) 'foss/2018a'
foss/2019a(23):ERROR:102: Tcl command execution failed: conflict foss

python/3.7.2-gcccore-8.2.0(43):ERROR:150: Module 'python/3.7.2-gcccore-8.2.0' conflicts with the currently loaded module(s) 'python/3.7.2-foss-2018a'
python/3.7.2-gcccore-8.2.0(43):ERROR:102: Tcl command execution failed: conflict python

gcc/8.3.0(24):ERROR:150: Module 'gcc/8.3.0' conflicts with the currently loaded module(s) 'gcc/6.4.0-2.28'
gcc/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcc

gcc/8.3.0(24):ERROR:150: Module 'gcc/8.3.0' conflicts with the currently loaded module(s) 'gcc/6.4.0-2.28'
gcc/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcc

openmpi/3.1.4-gcccuda-2019b(22):ERROR:150: Module 'openmpi/3.1.4-gcccuda-2019b' conflicts with the currently loaded module(s) 'openmpi/2.1.2-gcc-6.4.0-2.28'
openmpi/3.1.4-gcccuda-2019b(22):ERROR:102: Tcl command execution failed: conflict openmpi

openblas/0.3.7-gcc-8.3.0(22):ERROR:150: Module 'openblas/0.3.7-gcc-8.3.0' conflicts with the currently loaded module(s) 'openblas/0.2.20-gcc-6.4.0-2.28'
openblas/0.3.7-gcc-8.3.0(22):ERROR:102: Tcl command execution failed: conflict openblas

fftw/3.3.8-gompic-2019b(24):ERROR:150: Module 'fftw/3.3.8-gompic-2019b' conflicts with the currently loaded module(s) 'fftw/3.3.7-gompi-2018a'
fftw/3.3.8-gompic-2019b(24):ERROR:102: Tcl command execution failed: conflict fftw

scalapack/2.0.2-gompic-2019b(24):ERROR:150: Module 'scalapack/2.0.2-gompic-2019b' conflicts with the currently loaded module(s) 'scalapack/2.0.2-gompi-2018a-openblas-0.2.20'
scalapack/2.0.2-gompic-2019b(24):ERROR:102: Tcl command execution failed: conflict scalapack

gcc/8.3.0(24):ERROR:150: Module 'gcc/8.3.0' conflicts with the currently loaded module(s) 'gcc/6.4.0-2.28'
gcc/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcc

python/3.7.4-gcccore-8.3.0(47):ERROR:150: Module 'python/3.7.4-gcccore-8.3.0' conflicts with the currently loaded module(s) 'python/3.7.2-foss-2018a'
python/3.7.4-gcccore-8.3.0(47):ERROR:102: Tcl command execution failed: conflict python

python/3.7.4-gcccore-8.3.0(47):ERROR:150: Module 'python/3.7.4-gcccore-8.3.0' conflicts with the currently loaded module(s) 'python/3.7.2-foss-2018a'
python/3.7.4-gcccore-8.3.0(47):ERROR:102: Tcl command execution failed: conflict python

scipy-bundle/2019.10-fosscuda-2019b-python-3.7.4(28):ERROR:150: Module 'scipy-bundle/2019.10-fosscuda-2019b-python-3.7.4' conflicts with the currently loaded module(s) 'scipy-bundle/2019.03-foss-2019a'
scipy-bundle/2019.10-fosscuda-2019b-python-3.7.4(28):ERROR:102: Tcl command execution failed: conflict scipy-bundle

gcc/8.3.0(24):ERROR:150: Module 'gcc/8.3.0' conflicts with the currently loaded module(s) 'gcc/6.4.0-2.28'
gcc/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcc

openmpi/3.1.4-gcccuda-2019b(22):ERROR:150: Module 'openmpi/3.1.4-gcccuda-2019b' conflicts with the currently loaded module(s) 'openmpi/2.1.2-gcc-6.4.0-2.28'
openmpi/3.1.4-gcccuda-2019b(22):ERROR:102: Tcl command execution failed: conflict openmpi

zlib/1.2.11-gcccore-8.3.0(26):ERROR:150: Module 'zlib/1.2.11-gcccore-8.3.0' conflicts with the currently loaded module(s) 'zlib/1.2.11-foss-2018a'
zlib/1.2.11-gcccore-8.3.0(26):ERROR:102: Tcl command execution failed: conflict zlib

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

zlib/1.2.11-gcccore-8.3.0(26):ERROR:150: Module 'zlib/1.2.11-gcccore-8.3.0' conflicts with the currently loaded module(s) 'zlib/1.2.11-foss-2018a'
zlib/1.2.11-gcccore-8.3.0(26):ERROR:102: Tcl command execution failed: conflict zlib

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

hwloc/1.11.12-gcccore-8.3.0(38):ERROR:150: Module 'hwloc/1.11.12-gcccore-8.3.0' conflicts with the currently loaded module(s) 'hwloc/1.11.8-gcccore-6.4.0'
hwloc/1.11.12-gcccore-8.3.0(38):ERROR:102: Tcl command execution failed: conflict hwloc

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

sqlite/3.29.0-gcccore-8.3.0(22):ERROR:150: Module 'sqlite/3.29.0-gcccore-8.3.0' conflicts with the currently loaded module(s) 'sqlite/3.22.0-foss-2018a'
sqlite/3.29.0-gcccore-8.3.0(22):ERROR:102: Tcl command execution failed: conflict sqlite

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

bzip2/1.0.8-gcccore-8.3.0(30):ERROR:150: Module 'bzip2/1.0.8-gcccore-8.3.0' conflicts with the currently loaded module(s) 'bzip2/1.0.6-foss-2018a'
bzip2/1.0.8-gcccore-8.3.0(30):ERROR:102: Tcl command execution failed: conflict bzip2

zlib/1.2.11-gcccore-8.3.0(26):ERROR:150: Module 'zlib/1.2.11-gcccore-8.3.0' conflicts with the currently loaded module(s) 'zlib/1.2.11-foss-2018a'
zlib/1.2.11-gcccore-8.3.0(26):ERROR:102: Tcl command execution failed: conflict zlib

python/3.7.4-gcccore-8.3.0(47):ERROR:150: Module 'python/3.7.4-gcccore-8.3.0' conflicts with the currently loaded module(s) 'python/3.7.2-foss-2018a'
python/3.7.4-gcccore-8.3.0(47):ERROR:102: Tcl command execution failed: conflict python

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

zlib/1.2.11-gcccore-8.3.0(26):ERROR:150: Module 'zlib/1.2.11-gcccore-8.3.0' conflicts with the currently loaded module(s) 'zlib/1.2.11-foss-2018a'
zlib/1.2.11-gcccore-8.3.0(26):ERROR:102: Tcl command execution failed: conflict zlib

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

zlib/1.2.11-gcccore-8.3.0(26):ERROR:150: Module 'zlib/1.2.11-gcccore-8.3.0' conflicts with the currently loaded module(s) 'zlib/1.2.11-foss-2018a'
zlib/1.2.11-gcccore-8.3.0(26):ERROR:102: Tcl command execution failed: conflict zlib

zlib/1.2.11-gcccore-8.3.0(26):ERROR:150: Module 'zlib/1.2.11-gcccore-8.3.0' conflicts with the currently loaded module(s) 'zlib/1.2.11-foss-2018a'
zlib/1.2.11-gcccore-8.3.0(26):ERROR:102: Tcl command execution failed: conflict zlib

tensorboard 2.3.0 requires requests<3,>=2.21.0, which is not installed.
tensorflow 2.3.1 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.4 which is incompatible.
tensorboard 2.3.0 has requirement setuptools>=41.0.0, but you'll have setuptools 40.6.2 which is incompatible.
  The scripts f2py, f2py3 and f2py3.7 are installed in '/home/n9455647/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
tensorboard 2.3.0 requires requests<3,>=2.21.0, which is not installed.
tensorflow 2.3.1 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.4 which is incompatible.
tensorboard 2.3.0 has requirement setuptools>=41.0.0, but you'll have setuptools 40.6.2 which is incompatible.
  The scripts f2py, f2py3 and f2py3.7 are installed in '/home/n9455647/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Traceback (most recent call last):
  File "lstm_test.py", line 14, in <module>
    import stability as st
  File "/home/n9455647/PPM_Evaluation/Stability-Experiments/benchmark_interpretability/PPM_Stability/stability.py", line 22, in <module>
    import numpy as np
  File "/pkg/suse12/software/numpy/1.8.2-foss-2019a/lib/python2.7/site-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/pkg/suse12/software/numpy/1.8.2-foss-2019a/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/pkg/suse12/software/numpy/1.8.2-foss-2019a/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/pkg/suse12/software/numpy/1.8.2-foss-2019a/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/pkg/suse12/software/numpy/1.8.2-foss-2019a/lib/python2.7/site-packages/numpy/core/__init__.py", line 6, in <module>
    from . import multiarray
ImportError: dynamic module does not define module export function (PyInit_multiarray)
