gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

binutils/2.32-gcccore-8.3.0(22):ERROR:150: Module 'binutils/2.32-gcccore-8.3.0' conflicts with the currently loaded module(s) 'binutils/2.26-gcccore-5.4.0'
binutils/2.32-gcccore-8.3.0(22):ERROR:102: Tcl command execution failed: conflict binutils

cuda/10.1.243-gcc-8.3.0(28):ERROR:150: Module 'cuda/10.1.243-gcc-8.3.0' conflicts with the currently loaded module(s) 'cuda/9.0.176'
cuda/10.1.243-gcc-8.3.0(28):ERROR:102: Tcl command execution failed: conflict cuda

cuda/10.1.243-gcc-8.3.0(28):ERROR:150: Module 'cuda/10.1.243-gcc-8.3.0' conflicts with the currently loaded module(s) 'cuda/9.0.176'
cuda/10.1.243-gcc-8.3.0(28):ERROR:102: Tcl command execution failed: conflict cuda

zlib/1.2.11-gcccore-8.3.0(26):ERROR:150: Module 'zlib/1.2.11-gcccore-8.3.0' conflicts with the currently loaded module(s) 'zlib/1.2.8-intel-2016b'
zlib/1.2.11-gcccore-8.3.0(26):ERROR:102: Tcl command execution failed: conflict zlib

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

zlib/1.2.11-gcccore-8.3.0(26):ERROR:150: Module 'zlib/1.2.11-gcccore-8.3.0' conflicts with the currently loaded module(s) 'zlib/1.2.8-intel-2016b'
zlib/1.2.11-gcccore-8.3.0(26):ERROR:102: Tcl command execution failed: conflict zlib

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

cuda/10.1.243-gcc-8.3.0(28):ERROR:150: Module 'cuda/10.1.243-gcc-8.3.0' conflicts with the currently loaded module(s) 'cuda/9.0.176'
cuda/10.1.243-gcc-8.3.0(28):ERROR:102: Tcl command execution failed: conflict cuda

python/3.7.4-gcccore-8.3.0(47):ERROR:150: Module 'python/3.7.4-gcccore-8.3.0' conflicts with the currently loaded module(s) 'python/2.7.12-intel-2016b'
python/3.7.4-gcccore-8.3.0(47):ERROR:102: Tcl command execution failed: conflict python

h5py/2.10.0-fosscuda-2019b-python-3.7.4(26):ERROR:150: Module 'h5py/2.10.0-fosscuda-2019b-python-3.7.4' conflicts with the currently loaded module(s) 'h5py/2.6.0-intel-2016b-python-2.7.12-hdf5-1.8.17'
h5py/2.10.0-fosscuda-2019b-python-3.7.4(26):ERROR:102: Tcl command execution failed: conflict h5py

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

zlib/1.2.11-gcccore-8.3.0(26):ERROR:150: Module 'zlib/1.2.11-gcccore-8.3.0' conflicts with the currently loaded module(s) 'zlib/1.2.8-intel-2016b'
zlib/1.2.11-gcccore-8.3.0(26):ERROR:102: Tcl command execution failed: conflict zlib

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

sqlite/3.29.0-gcccore-8.3.0(22):ERROR:150: Module 'sqlite/3.29.0-gcccore-8.3.0' conflicts with the currently loaded module(s) 'sqlite/3.13.0-intel-2016b'
sqlite/3.29.0-gcccore-8.3.0(22):ERROR:102: Tcl command execution failed: conflict sqlite

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

bzip2/1.0.8-gcccore-8.3.0(30):ERROR:150: Module 'bzip2/1.0.8-gcccore-8.3.0' conflicts with the currently loaded module(s) 'bzip2/1.0.6-intel-2016b'
bzip2/1.0.8-gcccore-8.3.0(30):ERROR:102: Tcl command execution failed: conflict bzip2

zlib/1.2.11-gcccore-8.3.0(26):ERROR:150: Module 'zlib/1.2.11-gcccore-8.3.0' conflicts with the currently loaded module(s) 'zlib/1.2.8-intel-2016b'
zlib/1.2.11-gcccore-8.3.0(26):ERROR:102: Tcl command execution failed: conflict zlib

python/3.7.4-gcccore-8.3.0(47):ERROR:150: Module 'python/3.7.4-gcccore-8.3.0' conflicts with the currently loaded module(s) 'python/2.7.12-intel-2016b'
python/3.7.4-gcccore-8.3.0(47):ERROR:102: Tcl command execution failed: conflict python

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

zlib/1.2.11-gcccore-8.3.0(26):ERROR:150: Module 'zlib/1.2.11-gcccore-8.3.0' conflicts with the currently loaded module(s) 'zlib/1.2.8-intel-2016b'
zlib/1.2.11-gcccore-8.3.0(26):ERROR:102: Tcl command execution failed: conflict zlib

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/5.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

zlib/1.2.11-gcccore-8.3.0(26):ERROR:150: Module 'zlib/1.2.11-gcccore-8.3.0' conflicts with the currently loaded module(s) 'zlib/1.2.8-intel-2016b'
zlib/1.2.11-gcccore-8.3.0(26):ERROR:102: Tcl command execution failed: conflict zlib

zlib/1.2.11-gcccore-8.3.0(26):ERROR:150: Module 'zlib/1.2.11-gcccore-8.3.0' conflicts with the currently loaded module(s) 'zlib/1.2.8-intel-2016b'
zlib/1.2.11-gcccore-8.3.0(26):ERROR:102: Tcl command execution failed: conflict zlib

DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
  ERROR: Could not find a version that satisfies the requirement lime==0.2.0.1 (from versions: 0.1.1.1, 0.1.1.2, 0.1.1.3, 0.1.1.4, 0.1.1.5, 0.1.1.6, 0.1.1.7, 0.1.1.9, 0.1.1.10, 0.1.1.11, 0.1.1.12, 0.1.1.13, 0.1.1.14, 0.1.1.15, 0.1.1.16, 0.1.1.17, 0.1.1.18, 0.1.1.19, 0.1.1.20, 0.1.1.21, 0.1.1.22, 0.1.1.23, 0.1.1.24, 0.1.1.25, 0.1.1.26, 0.1.1.27, 0.1.1.28, 0.1.1.29, 0.1.1.30, 0.1.1.31, 0.1.1.32, 0.1.1.33, 0.1.1.34, 0.1.1.35, 0.1.1.36, 0.1.1.37, 0.2.0.0)
ERROR: No matching distribution found for lime==0.2.0.1
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
  WARNING: The script tqdm is installed in '/home/n9455647/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
ERROR: PyYAML requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*' but the running Python is 3.4.6
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Traceback (most recent call last):
  File "lstm_test.py", line 8, in <module>
    import EncoderFactory
  File "/home/n9455647/PPM_Evaluation/Stability-Experiments/benchmark_interpretability/PPM_Stability/EncoderFactory.py", line 1, in <module>
    from transformers.StaticTransformer import StaticTransformer
  File "/home/n9455647/PPM_Evaluation/Stability-Experiments/benchmark_interpretability/PPM_Stability/transformers/StaticTransformer.py", line 1, in <module>
    from sklearn.base import TransformerMixin
  File "/home/n9455647/.local/lib/python3.4/site-packages/sklearn/__init__.py", line 64, in <module>
    from .base import clone
  File "/home/n9455647/.local/lib/python3.4/site-packages/sklearn/base.py", line 11, in <module>
    import numpy as np
  File "/pkg/suse12/software/python/2.7.12-intel-2016b/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/pkg/suse12/software/python/2.7.12-intel-2016b/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/pkg/suse12/software/python/2.7.12-intel-2016b/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/pkg/suse12/software/python/2.7.12-intel-2016b/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/pkg/suse12/software/python/2.7.12-intel-2016b/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: dynamic module does not define init function (PyInit_multiarray)
